
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author navee
 */
public class adddatawindow extends javax.swing.JFrame {

    /**
     */
    public adddatawindow() {
        initComponents();
    }

        public adddatawindow(HomeFrame homeFrame) {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        savebutton = new javax.swing.JButton();
        sofaidtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pricetf = new javax.swing.JTextField();
        sofanametf = new javax.swing.JTextField();
        catogorycombobox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        clearbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        availabilitytf = new javax.swing.JTextField();
        WhiteR = new javax.swing.JRadioButton();
        BlackR = new javax.swing.JRadioButton();
        BrownR = new javax.swing.JRadioButton();
        CreamR = new javax.swing.JRadioButton();
        dblueR = new javax.swing.JRadioButton();
        GreyR = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        savebutton.setBackground(new java.awt.Color(0, 0, 153));
        savebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 255, 0));
        savebutton.setText("SAVE");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 138, 43));

        sofaidtf.setBackground(new java.awt.Color(255, 255, 255));
        sofaidtf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sofaidtf.setForeground(new java.awt.Color(0, 0, 153));
        sofaidtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.add(sofaidtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 252, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("SOFA ID      :-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 52, 101, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("CATEGORY  :-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("SOFA NAME:-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 194, 101, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("COLOURS    :-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 101, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("PRICE           :-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        Pricetf.setBackground(new java.awt.Color(255, 255, 255));
        Pricetf.setForeground(new java.awt.Color(0, 0, 153));
        Pricetf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        Pricetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PricetfActionPerformed(evt);
            }
        });
        jPanel1.add(Pricetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 252, 32));

        sofanametf.setBackground(new java.awt.Color(255, 255, 255));
        sofanametf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sofanametf.setForeground(new java.awt.Color(0, 0, 153));
        sofanametf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.add(sofanametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 252, 32));

        catogorycombobox.setBackground(new java.awt.Color(255, 255, 255));
        catogorycombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        catogorycombobox.setForeground(new java.awt.Color(0, 0, 153));
        catogorycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arm Chair", "Love Seat", "Sofa Bed", "Sectional Sofa", "Chaise Lounge" }));
        catogorycombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catogorycomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(catogorycombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 252, 36));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Enter Details Of New Items!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 6, -1, -1));

        clearbutton.setBackground(new java.awt.Color(0, 0, 153));
        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 0));
        clearbutton.setText("CLEAR");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 138, 43));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Availability     :-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 120, -1));

        availabilitytf.setBackground(new java.awt.Color(255, 255, 255));
        availabilitytf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        availabilitytf.setForeground(new java.awt.Color(0, 0, 153));
        availabilitytf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        availabilitytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabilitytfActionPerformed(evt);
            }
        });
        jPanel1.add(availabilitytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 250, 32));

        WhiteR.setBackground(new java.awt.Color(255, 255, 255));
        WhiteR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WhiteR.setForeground(new java.awt.Color(0, 0, 153));
        WhiteR.setText("White");
        jPanel1.add(WhiteR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        BlackR.setBackground(new java.awt.Color(255, 255, 255));
        BlackR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BlackR.setForeground(new java.awt.Color(0, 0, 153));
        BlackR.setText("Black");
        jPanel1.add(BlackR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        BrownR.setBackground(new java.awt.Color(255, 255, 255));
        BrownR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BrownR.setForeground(new java.awt.Color(0, 0, 153));
        BrownR.setText("Brown");
        jPanel1.add(BrownR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        CreamR.setBackground(new java.awt.Color(255, 255, 255));
        CreamR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreamR.setForeground(new java.awt.Color(0, 0, 153));
        CreamR.setText("Cream");
        jPanel1.add(CreamR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        dblueR.setBackground(new java.awt.Color(255, 255, 255));
        dblueR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dblueR.setForeground(new java.awt.Color(0, 0, 153));
        dblueR.setText("Dark Blue");
        jPanel1.add(dblueR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        GreyR.setBackground(new java.awt.Color(255, 255, 255));
        GreyR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GreyR.setForeground(new java.awt.Color(0, 0, 153));
        GreyR.setText("Grey");
        jPanel1.add(GreyR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catogorycomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catogorycomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catogorycomboboxActionPerformed

    private void PricetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PricetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PricetfActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        Clear();
        
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void availabilitytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabilitytfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availabilitytfActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {                                           
         String sofaid = sofaidtf.getText();
         String sofaname = sofanametf.getText();
         String price = Pricetf.getText();
         String availability = availabilitytf.getText();
         String category = catogorycombobox.getSelectedItem().toString();
         String colour = null;
        if (sofaid.isEmpty() || sofaname.isEmpty() || price.isEmpty() || availability.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the relavent fields & Try again!","Error!", JOptionPane.ERROR_MESSAGE);
            return;
            
            }else if (BlackR.isSelected()) {
                colour = "Black";
            }else if (dblueR.isSelected()) {
                colour = "Dark Blue";
                 
            } else if (GreyR.isSelected()) {
                colour = "Gray";
                 
            } else if (CreamR.isSelected()) {
                colour = "Cream";
                   
            } else if (BrownR.isSelected()) {
                colour = "Brown";
                 
            } else if (WhiteR.isSelected()) {
                colour = "Brown";
            } else {
            JOptionPane.showMessageDialog(this, "Please select a color!");
               return; // stop if no color selected
            

        }try { 
            Double.valueOf(price);
            Integer.valueOf(availability);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Price & Availability must be a number!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
         HomeFrame.addrow(new Object[]{sofaid, category, sofaname, colour, price, availability});
         
         try (FileWriter fw = new FileWriter("src/sofa_inventory.csv", true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter out = new PrintWriter(bw)) {

            out.println(sofaid + "," + category + "," + sofaname + "," + colour + "," + price + "," + availability);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "inventory Update Failed" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this, "The inventory updated successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
    Clear(); // optional method to clear text fields

         
    }
        
    public void Clear()
    {
        sofaidtf.setText ("");
        sofanametf.setText ("");
        BlackR.setSelected(false);
        BrownR.setSelected(false);
        dblueR.setSelected(false);
        GreyR.setSelected(false);
        WhiteR.setSelected(false);
        CreamR.setSelected(false);
        availabilitytf.setText ("");
        Pricetf.setText ("");


    }

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
          
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BlackR;
    private javax.swing.JRadioButton BrownR;
    private javax.swing.JRadioButton CreamR;
    private javax.swing.JRadioButton GreyR;
    private javax.swing.JTextField Pricetf;
    private javax.swing.JRadioButton WhiteR;
    private javax.swing.JTextField availabilitytf;
    private javax.swing.JComboBox<String> catogorycombobox;
    private javax.swing.JButton clearbutton;
    private javax.swing.JRadioButton dblueR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField sofaidtf;
    private javax.swing.JTextField sofanametf;
    // End of variables declaration//GEN-END:variables
}
